const ALL = "ALL"
const SHORT = "SHORT";
const LONG = "LONG";
const BEGINNER = 'BEGINNER';
const FAMILIAR = 'FAMILIAR';
const EXPERIENCED = "EXPERIENCED";
const EXPERT = "EXPERT";

//API FIELDS
const USERNAME = 'username';
const PUBLIC_FEED = "PUBLIC_FEED";

//FEED FIELDS
const PARENT = 'PARENT';
const SIBLINGS = 'SIBLINGS';
const CHILDREN = 'CHILDREN';
const FOLLOWERS = 'FOLLOWERS';

module.exports = {
    ALL,
    SHORT,
    LONG,

    PUBLIC_FEED,
    USERNAME,

    PARENT,
    SIBLINGS,
    CHILDREN,
    FOLLOWERS,

    BEGINNER,
    FAMILIAR,
    EXPERIENCED,
    EXPERT
}